### PR TITLE
refactor: Move UpdateAndGet/Select implementations to API

### PR DESCRIPTION
**Pull request by jwatson-ccc**

### CODE REVIEW

**Comment by jwatson-ccc** [comment]
I have tested this in a project but have yet to write any unit tests. We will eventually write unit tests.

**Review by bswaney-ccc — APPROVED** [review]
LGTM
Note: In api.go on line#: 35, 36, the comment references a "scanapi", it looks like this may have been left over from an earlier iteration?

**Comment by jwatson-ccc** [comment]
> LGTM Note: In api.go on line#: 35, 36, the comment references a "scanapi", it looks like this may have been left over from an earlier iteration?

@bswaney-ccc Fixed. Ready for review again.

**Review by bswaney-ccc — APPROVED** [review]
LGTM

**Pull request merged**
